spring:
  application:
    name: recipe

  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

  # .env import
  config:
    import: optional:file:.env[.properties], classpath:application-jwt.yaml, classpath:application-oauth.yaml

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini



  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: ${JPA_DDI:true}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000
      mail.smtp.starttls.required: true
      #mail.starttls.enable: true
      mail.smtp.auth: true

logging:
  level:
    org:
      springframework:
        security: TRACE

app:
  domain: ${APP_DOMAIN:http://localhost:8080}

