spring:
  application:
    name: recipe

  sql:
    init:
      mode: never

  # .env import
  config:
    import: optional:file:.env[.properties], classpath:application-jwt.yaml

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        security: TRACE
