spring:
  application:
    name: recipeㅅ


  sql:
    init:
      mode: always

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3307/oauth2}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        security: TRACE
